import { MenuItem } from './types';
import chickenPic from './assets/images/chicken_pizza_1780999784524.png';
import cheesePic from './assets/images/cheese_pizza_1780999802064.png';
import zingerPic from './assets/images/zinger_burger_1780999819356.png';
import dealPic from './assets/images/pizza_deal_1780999837854.png';
import calzonePic from './assets/images/calzone_chunks_1780999859462.png';

export const menuItems: MenuItem[] = [
  {
    id: 'p1',
    name: 'Chicken Lover',
    description: 'Black Olives, Onion, Tomato, Green Olives',
    price: 1500,
    category: 'Pizza',
    image: chickenPic,
    isBestSeller: true,
  },
  {
    id: 'p2',
    name: 'Cheese Lover',
    description: 'Extra Cheese, Onion',
    price: 1400,
    category: 'Pizza',
    image: cheesePic,
  },
  {
    id: 'p3',
    name: 'Chicken Tikka',
    description: 'Tikka Chunks, Onion, Jalapenos',
    price: 1500,
    category: 'Pizza',
    image: chickenPic,
    isBestSeller: true,
  },
  {
    id: 'p4',
    name: 'Fajita',
    description: 'Fajita Meat Capsicum, Onion Tomato, Jalapenos',
    price: 1600,
    category: 'Pizza',
    image: chickenPic,
  },
  {
    id: 'p5',
    name: 'Chicken Supreme',
    description: 'Smoked Chicken, Chicken Sausages, Olives, Mushroom',
    price: 1700,
    category: 'Pizza',
    image: chickenPic,
  },
  {
    id: 'p6',
    name: 'Vegetable Pizza',
    description: 'Onion, Capsicum, Olives, Mushroom, Tomato',
    price: 1300,
    category: 'Pizza',
    image: cheesePic,
  },
  {
    id: 'p7',
    name: 'Hot & Spicy Tikka',
    description: 'Special Spicy Tikka, Onion, Jalapenos',
    price: 1600,
    category: 'Pizza',
    image: chickenPic,
  },
  {
    id: 'd1',
    name: 'Deal 1',
    description: '1 Regular Pizza, 2 Zinger Burgers, 1.5 Liter Drink',
    price: 2450,
    category: 'Deals',
    image: dealPic,
    isBestSeller: true,
  },
  {
    id: 'd2',
    name: 'Deal 2',
    description: '2 Regular Pizzas, 1.5 Liter Drink',
    price: 2450,
    category: 'Deals',
    image: dealPic,
  },
  {
    id: 'd3',
    name: 'Deal 3',
    description: '3 Regular Pizzas, 1.5 Liter Drink',
    price: 3750,
    category: 'Deals',
    image: dealPic,
  },
  {
    id: 'd4',
    name: 'Deal 4',
    description: '1 Large Pizza, 1 Regular Drink',
    price: 2050,
    category: 'Deals',
    image: dealPic,
  },
  {
    id: 'd5',
    name: 'Deal 5',
    description: '2 Large Pizzas, 1.5 Liter Drink',
    price: 3850,
    category: 'Deals',
    image: dealPic,
  },
  {
    id: 'd6',
    name: 'Deal 6',
    description: '1 Extra Large Pizza, 1.5 Liter Drink',
    price: 4950,
    category: 'Deals',
    image: dealPic,
  },
  {
    id: 's1',
    name: 'Calzoni Chunks',
    description: 'Delicious Calzoni',
    price: 750,
    category: 'Sides',
    image: calzonePic,
  },
  {
    id: 's2',
    name: 'Cheese Sticks',
    description: 'Crispy Cheese Sticks',
    price: 550,
    category: 'Sides',
    image: calzonePic,
  },
  {
    id: 's3',
    name: 'Zinger Burger',
    description: 'Classic Zinger Burger',
    price: 450,
    category: 'Sides',
    image: zingerPic,
    isBestSeller: true,
  },
  {
    id: 's4',
    name: 'Hot Wings',
    description: '6 pieces Hot Wings',
    price: 400,
    category: 'Sides',
    image: zingerPic,
  },
];
